//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICYL.API.Repository
{
	using Microsoft.EntityFrameworkCore;
	using System;
	using System.Data.Entity;
	//using System.Data.Entity;
	//using System.Data.Entity.Infrastructure;
	//using System.Data.Entity.Core.Objects;
	using System.Linq;
    
    public partial class ICYLEntities //: DbContext
    {
        //public ICYLEntities()
        //    : base("name=ICYLEntities")
        //{
        //}
    
        //protected override void OnModelCreating(DbModelBuilder modelBuilder)
        //{
        //    throw new UnintentionalCodeFirstException();
        //}
    
        //public virtual DbSet<PaymentConfig> PaymentConfigs { get; set; }
        //public virtual DbSet<PaymentTransaction> PaymentTransactions { get; set; }
        //public virtual DbSet<LookupGroup> LookupGroups { get; set; }
        //public virtual DbSet<LookupValue> LookupValues { get; set; }
        //public virtual DbSet<PaymentBatch> PaymentBatches { get; set; }
        //public virtual DbSet<ICYLEmail> ICYLEmails { get; set; }
    
        //public virtual ObjectResult<ICYLReceipt_Result> ICYLReceipt()
        //{
        //    return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ICYLReceipt_Result>("ICYLReceipt");
        //}
    }
}
