//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICYL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentTransaction
    {
        public int TransactionId { get; set; }
        public decimal AmtTransaction { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int PaymentConfigId { get; set; }
        public string TransId { get; set; }
        public string TransResponseCode { get; set; }
        public string TransMessageCode { get; set; }
        public string TransDescription { get; set; }
        public string TransAuthCode { get; set; }
        public string TransErrorCode { get; set; }
        public string TransErrorText { get; set; }
        public Nullable<int> BatchId { get; set; }
        public string CustomerProfileId { get; set; }
        public string CustomerAddressId { get; set; }
    }
}
