//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICYL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentBatch
    {
        public int BatchId { get; set; }
        public Nullable<System.DateTime> settlementTimeUTC { get; set; }
        public Nullable<System.DateTime> settlementTimeLocal { get; set; }
        public string settlementState { get; set; }
        public string marketType { get; set; }
        public string product { get; set; }
    }
}
