//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICYL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentConfig
    {
        public decimal AmtDonation { get; set; }
        public decimal AmtTransactionPaid { get; set; }
        public string RecurringType { get; set; }
        public Nullable<bool> IsCreditCard { get; set; }
        public Nullable<bool> IsECheck { get; set; }
        public Nullable<bool> IsMailInCheck { get; set; }
        public Nullable<bool> IsAnonymous { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string CompanyName { get; set; }
        public string EmailId { get; set; }
        public string Comments { get; set; }
        public string PhoneNumber { get; set; }
        public int lkpDonationCategory { get; set; }
        public string BillingAddressLine1 { get; set; }
        public string BillingAddressLine2 { get; set; }
        public string BillingCity { get; set; }
        public string BillingState { get; set; }
        public string BillingZip { get; set; }
        public string BillingCountry { get; set; }
        public string CCNum { get; set; }
        public string CCCvc { get; set; }
        public string CCHolderName { get; set; }
        public string CCExpiry { get; set; }
        public string BankRoutingNum { get; set; }
        public string BankAccountNum { get; set; }
        public string BankNameOnAccount { get; set; }
        public string BankAccountType { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public int PaymentConfigId { get; set; }
        public Nullable<int> PaymentType { get; set; }
        public string SubscriptionTransId { get; set; }
        public string SubscriptionResponseCode { get; set; }
        public string SubscriptionResponseText { get; set; }
        public string MailingAddressLine1 { get; set; }
        public string MailingAddressLine2 { get; set; }
        public string MailingCity { get; set; }
        public string MailingState { get; set; }
        public string MailingZip { get; set; }
        public string MailingCountry { get; set; }
        public string CustomerProfileId { get; set; }
        public string CustomerAddressId { get; set; }
        public Nullable<System.DateTime> dtPaymentStart { get; set; }
        public Nullable<System.DateTime> dtPaymentEnd { get; set; }
        public Nullable<int> PaymentEndType { get; set; }
        public Nullable<int> PaymentMaxOccurences { get; set; }
        public Nullable<bool> isDownloaded { get; set; }
        public string RecurringInterval { get; set; }
    }
}
